name: IdeaWeaver Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install torch in system Python
      run: |
        pip install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Setup IdeaWeaver Environment
      run: |
        chmod +x setup_environments.sh
        yes | ./setup_environments.sh
    
    - name: Run basic CLI tests
      run: |
        source ideaweaver-env/bin/activate
        ideaweaver --help
        